INSERT INTO flight_application.extra_feature
(name) VALUES
	('Complimentary Wi-Fi'),
    ('Seat-back Screens'),
    ('Free Snacks'),
    ('Free Breakfast'),
    ('Seat Reservation'),
    ('Fast Track'),
    ('In-flight Magazine'),
    ('Extra Legroom'),
    ('Complimentary Meals'),
    ('Lounge Access'),
    ('Enhanced Entertainment System'),
    ('Priority Boarding'),
    ('Lounge Access'),
    ('Swiss Chocolates'),
    ('Priority Check-in'),
    ('Complimentary Drinks'),
    ('Italian Cuisine'),
    ('Reserved Overhead Space'),
    ('Alitalia Lounges'),
    ('Wi-Fi'),
    ('On-demand Video'),
    ('Lounges Access'),
    ('Michelin-starred Menus'),
    ('Personal Coat Service'),
    ('Flat-bed Seats'),
    ('Shower Spas'),
    ('Award-winning Cuisine'),
    ('Fully Lie-flat Beds'),
    ('4000 Entertainment Options'),
    ('Book the Cook Service'),
    ('Givenchy Amenities'),
    ('Standalone Beds');