package ntnu.no.stud.entities;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

/**
 * Represents an airport entity in the database.
 * Each airport has a unique ID, a 3-letter airport code, and an associated
 * city.
 */
@Entity
@Table(name = "airport")
public class Airport {

    /**
     * The unique identifier for the airport.
     * Automatically generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int id;

    /**
     * The 3-letter code representing the airport (e.g., "LAX", "JFK").
     */
    @Column(name = "airport_code", length = 3)
    private String airportCode;

    /**
     * The city where the airport is located.
     */
    @Column(name = "city", nullable = false)
    private String city;

    public Airport() {
    }

    /**
     * Constructs an Airport with the given code and city.
     *
     * @param airportCode The 3-letter airport code.
     * @param city        The city where the airport is located.
     */
    public Airport(String airportCode, String city) {
        this.airportCode = airportCode;
        this.city = city;
    }

    /**
     * Returns the unique ID of the airport.
     *
     * @return the airport ID
     */
    public int getId() {
        return id;
    }

    /**
     * Sets the unique ID of the airport.
     *
     * @param id the ID to set
     */
    public void setId(int id) {
        this.id = id;
    }

    /**
     * Returns the 3-letter airport code.
     *
     * @return the airport code
     */
    public String getAirportCode() {
        return airportCode;
    }

    /**
     * Sets the 3-letter airport code.
     *
     * @param airportCode the code to set
     */
    public void setAirportCode(String airportCode) {
        this.airportCode = airportCode;
    }

    /**
     * Returns the city where the airport is located.
     *
     * @return the city name
     */
    public String getCity() {
        return city;
    }

    /**
     * Sets the city where the airport is located.
     *
     * @param city the city name to set
     */
    public void setCity(String city) {
        this.city = city;
    }
}
