package ntnu.no.stud.entities;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

/**
 * Represents an airplane class entity stored in the database.
 * Each class has a unique ID and name.
 * 
 * Example: Economy or Business
 */
@Entity
@Table(name = "class")
public class ClassEntity {

    /**
     * Unique identifier for the class. Auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int id;

    /**
     * Name of the class. Must be unique and not null.
     */
    @Column(name = "name", nullable = false, unique = true)
    private String name;

    /**
     * Default constructor required by JPA.
     */
    public ClassEntity() {
    }

    /**
     * Constructs a new ClassEntity with the specified name.
     *
     * @param name the name of the seating class
     */
    public ClassEntity(String name) {
        this.name = name;
    }

    /**
     * Returns the unique identifier of the class.
     *
     * @return the ID of the class
     */
    public int getId() {
        return id;
    }

    /**
     * Sets the unique identifier of the class.
     *
     * @param id the ID to set
     */
    public void setId(int id) {
        this.id = id;
    }

    /**
     * Returns the name of the class.
     *
     * @return the name of the class
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the name of the class.
     *
     * @param name the name to set
     */
    public void setName(String name) {
        this.name = name;
    }
}
