package ntnu.no.stud.entities;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

/**
 * Represents an extra feature that can be associated with a flight.
 * Each feature has a unique identifier and a name.
 */
@Entity
@Table(name = "extra_feature")
public class ExtraFeature {

    /**
     * Unique identifier for the class. Auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int id;

    /**
     * Name of the extra feature.
     */
    private String name;

    /**
     * Default constructor required by JPA.
     */
    public ExtraFeature() {
    }

    /**
     * Constructs a new ExtraFeature with the specified name.
     *
     * @param name the name of the extra feature
     */
    public ExtraFeature(String name) {
        this.name = name;
    }

    /**
     * Returns the unique identifier of the extra feature.
     *
     * @return the ID of the extra feature
     */
    public int getId() {
        return id;
    }

    /**
     * Sets the unique identifier of the extra feature.
     *
     * @param id the ID to set
     */
    public void setId(int id) {
        this.id = id;
    }

    /**
     * Returns the name of the extra feature.
     *
     * @return the name of the extra feature
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the name of the extra feature.
     *
     * @param name the name to set
     */
    public void setName(String name) {
        this.name = name;
    }
}
