package ntnu.no.stud.entities;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Table;
import jakarta.persistence.Id;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.JoinColumn;

/**
 * Represents a user's favorite flight entry.
 * Each favorite is linked to a specific user and a specific flight.
 */
@Entity
@Table(name = "favorite_flights")
public class FavoriteFlight {

    /**
     * The unique identifier for the favorite flight entry.
     * Automatically generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int id;

    /**
     * The user who marked the flight as favorite.
     */
    @ManyToOne
    @JoinColumn(name = "user_id", nullable = false)
    private User user;

    /**
     * The flight that was marked as favorite.
     */
    @ManyToOne
    @JoinColumn(name = "flight_id", nullable = false)
    private Flight flight;

    public FavoriteFlight() { }

    /**
     * Constructs a FavoriteFlight with the specified user and flight.
     *
     * @param user The user who favorited the flight.
     * @param flight The flight that is favorited.
     */
    public FavoriteFlight(User user, Flight flight) {
        this.user = user;
        this.flight = flight;
    }

    // Getters and setters
    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public User getUser() {
        return user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    public Flight getFlight() {
        return flight;
    }

    public void setFlight(Flight flight) {
        this.flight = flight;
    }
}

