package ntnu.no.stud.entities;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Table;
import jakarta.persistence.Id;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.JoinColumn;

/**
 * Represents a user's favorite price (flight offer).
 * Each favorite is linked to a specific user and a specific price.
 */
@Entity
@Table(name = "favorite_flights")
public class FavoriteFlight {

    /**
     * The unique identifier for the favorite flight entry.
     * Automatically generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int id;

    /**
     * The user who marked the price as favorite.
     */
    @ManyToOne
    @JoinColumn(name = "user_id", nullable = false)
    private User user;

    /**
     * The price (flight offer) that was marked as favorite.
     */
    @ManyToOne
    @JoinColumn(name = "price_id", nullable = false)
    private Price price;

    public FavoriteFlight() { }

    /**
     * Constructs a FavoriteFlight with the specified user and price.
     *
     * @param user The user who favorited the price.
     * @param price The price that is favorited.
     */
    public FavoriteFlight(User user, Price price) {
        this.user = user;
        this.price = price;
    }

    /**
     * Returns the ID of the favorite flight entry.
     *
     * @return the ID of this favorite
     */
    public int getId() {
        return id;
    }

    /**
     * Sets the ID of this favorite flight entry.
     *
     * @param id the new ID to assign
     */
    public void setId(int id) {
        this.id = id;
    }

    /**
     * Returns the user who favorited the flight price.
     *
     * @return the user
     */
    public User getUser() {
        return user;
    }

    /**
     * Sets the user who favorited the flight price.
     *
     * @param user the user to associate with this favorite
     */
    public void setUser(User user) {
        this.user = user;
    }

    /**
     * Returns the favorited flight price.
     *
     * @return the price
     */
    public Price getPrice() {
        return price;
    }

    /**
     * Sets the flight price that is marked as favorite.
     *
     * @param price the price to associate with this favorite
     */
    public void setPrice(Price price) {
        this.price = price;
    }
}
