package ntnu.no.stud.entities;

import com.fasterxml.jackson.annotation.JsonIgnore;

import jakarta.persistence.*;

/**
 * Represents an airline company stored in the database.
 * Each company has a unique name and abbreviation, along with optional branding
 * details
 * like a website, image URL, and image data.
 */
@Entity
@Table(name = "flight_company")
public class FlightCompany {

    /**
     * Unique identifier for the flight company.
     * This value is auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", nullable = false)
    private int id;

    /**
     * Full name of the flight company.
     * Must be unique and not null.
     */
    @Column(name = "name", nullable = false, unique = true)
    private String name;

    /**
     * Unique abbreviation of the company name (e.g., "KLM", "SAS").
     */
    @Column(name = "abbreviation", nullable = false, unique = true)
    private String abbreviation;

    /**
     * Official website URL of the flight company.
     */
    @Column(name = "website_url")
    private String websiteUrl;

    /**
     * URL pointing to an image (e.g., banner image) related to the company.
     */
    @Column(name = "image_url")
    private String imageUrl;

    /**
     * Raw image data (e.g., a banner image) associated with the company, stored as
     * binary.
     */
    @JsonIgnore
    @Lob
    @Basic(fetch = FetchType.LAZY)
    @Column(name = "image_data", columnDefinition = "MEDIUMBLOB")
    private byte[] imageData;

    /**
     * Raw logo image data for the company, stored as binary.
     */
    @Lob
    @Column(name = "logo_image_data", columnDefinition = "MEDIUMBLOB")
    private byte[] logoImageData;

    /**
     * Default constructor required by JPA.
     */
    public FlightCompany() {
    }

    /**
     * Constructs a new FlightCompany with the specified details.
     *
     * @param name          the full name of the company
     * @param websiteUrl    the website URL of the company
     * @param imageUrl      the image URL of the company
     * @param imageData     the binary image data
     * @param logoImageData the binary logo image data
     * @param abbreviation  the unique abbreviation for the company
     */
    public FlightCompany(String name, String websiteUrl, String imageUrl, byte[] imageData, byte[] logoImageData,
            String abbreviation) {
        this.name = name;
        this.websiteUrl = websiteUrl;
        this.imageUrl = imageUrl;
        this.imageData = imageData;
        this.logoImageData = logoImageData;
        this.abbreviation = abbreviation;
    }

    /**
     * Returns the unique ID of the flight company.
     *
     * @return the company ID
     */
    public int getId() {
        return id;
    }

    /**
     * Returns the name of the company.
     *
     * @return the company name
     */
    public String getName() {
        return name;
    }

    /**
     * Returns the abbreviation of the company.
     *
     * @return the company abbreviation
     */
    public String getAbbreviation() {
        return abbreviation;
    }

    /**
     * Returns the website URL of the company.
     *
     * @return the website URL
     */
    public String getWebsiteUrl() {
        return websiteUrl;
    }

    /**
     * Returns the image URL of the company.
     *
     * @return the image URL
     */
    public String getImageUrl() {
        return imageUrl;
    }

    /**
     * Returns the raw image data of the company.
     *
     * @return the image data
     */
    public byte[] getImageData() {
        return imageData;
    }

    /**
     * Returns the raw logo image data of the company.
     *
     * @return the logo image data
     */
    public byte[] getLogoImageData() {
        return logoImageData;
    }

    /**
     * Sets the unique ID of the flight company.
     *
     * @param id the ID to set
     */
    public void setId(int id) {
        this.id = id;
    }

    /**
     * Sets the name of the company.
     *
     * @param name the name to set
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Sets the abbreviation of the company.
     *
     * @param abbreviation the abbreviation to set
     */
    public void setAbbreviation(String abbreviation) {
        this.abbreviation = abbreviation;
    }

    /**
     * Sets the website URL of the company.
     *
     * @param websiteUrl the URL to set
     */
    public void setWebsiteUrl(String websiteUrl) {
        this.websiteUrl = websiteUrl;
    }

    /**
     * Sets the image URL of the company.
     *
     * @param imageUrl the URL to set
     */
    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl;
    }

    /**
     * Sets the raw image data of the company.
     *
     * @param imageData the image data to set
     */
    public void setImageData(byte[] imageData) {
        this.imageData = imageData;
    }

    /**
     * Sets the raw logo image data of the company.
     *
     * @param logoImageData the logo image data to set
     */
    public void setLogoImageData(byte[] logoImageData) {
        this.logoImageData = logoImageData;
    }

    /**
     * Returns a short string representation of the flight company.
     *
     * @return a string with the company ID and name
     */
    @Override
    public String toString() {
        return "FlightCompany{id=" + id + ", name='" + name + "'}";
    }
}
