package ntnu.no.stud.entities;

import jakarta.persistence.*;

/**
 * Represents a flight with basic identifying information such as name and
 * company.
 * This entity maps to the "flight" table in the database.
 */
@Entity
@Table(name = "flight")
public class Flight {

    /**
     * The unique identifier for the flight.
     * Automatically generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", nullable = false)
    private int id;

    /**
     * The name of the flight (e.g., flight number or route name).
     */
    @Column(name = "name", nullable = false)
    private String name;

    /**
     * The airline company operating the flight.
     */
    @ManyToOne(optional = false)
    @JoinColumn(name = "company_id", referencedColumnName = "id")
    private FlightCompany company;

    public Flight() {
    }

    /**
     * Constructs a Flight with the specified name and company.
     *
     * @param name    the name of the flight.
     * @param company the company operating the flight.
     */
    public Flight(String name, FlightCompany company) {
        this.name = name;
        this.company = company;
    }

    /**
     * Returns the unique identifier of the flight.
     *
     * @return the flight ID
     */
    public int getId() {
        return id;
    }

    /**
     * Sets the unique identifier of the flight.
     *
     * @param id the ID to assign
     */
    public void setId(int id) {
        this.id = id;
    }

    /**
     * Returns the name of the flight.
     *
     * @return the flight name
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the name of the flight.
     *
     * @param name the flight name to assign
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Returns the airline company operating the flight.
     *
     * @return the operating {@link FlightCompany}
     */
    public FlightCompany getCompany() {
        return company;
    }

    /**
     * Sets the airline company operating the flight.
     *
     * @param company the {@link FlightCompany} to associate
     */
    public void setCompany(FlightCompany company) {
        this.company = company;
    }

    /**
     * Returns a string representation of the flight.
     *
     * @return a string describing the flight
     */
    @Override
    public String toString() {
        return "Flight{id=" + id + ", name='" + name + "', company='" + company.getName() + "'}";
    }
}
