package ntnu.no.stud.entities;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

/**
 * Represents a flight with basic identifying information such as name and company.
 * This entity maps to the "flight" table in the database.
 */
@Entity
@Table(name = "flight")
public class Flight {

    /**
     * The unique identifier for the flight.
     * Automatically generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", nullable = false)
    private int id;

    /**
     * The name of the flight (e.g., flight number or route name).
     */
    @Column(name = "name", nullable = false)
    private String name;

    /**
     * The airline company operating the flight.
     */
    @Column(name = "company", nullable = false)
    private String company;

    public Flight() { }

    /**
     * Constructs a Flight with the specified name and company.
     *
     * @param name the name of the flight.
     * @param company the company operating the flight.
     */
    public Flight(String name, String company) {
        this.name = name;
        this.company = company;
    }

    // Getters and Setters
    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getCompany() {
        return company;
    }

    public void setCompany(String company) {
        this.company = company;
    }

    @Override
    public String toString() {
        return "Flight{id=" + id + ", name='" + name + "', company='" + company + "'}";
    }
}
