package ntnu.no.stud.entities;

import jakarta.persistence.Entity;
import jakarta.persistence.Table;
import jakarta.persistence.Id;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Column;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.JoinColumn;

/**
 * Represents a product.
 */
@Entity
@Table(name = "price")
public class Price {

    /**
     * The unique identifier for the price.
     * Automatically generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int id;

    /**
     * The flight class associated with this price.
     */
    @ManyToOne
    @JoinColumn(name = "class_id", nullable = false)
    private FlightClasses flightClassId;

    /**
     * The price of the flight.
     */
    @Column(name = "price", nullable = false)
    private int price;

    /**
     * The currency code for the price (e.g., USD, EUR).
     */
    @Column(name = "currency_code", length = 3)
    private String currencyCode;

    /**
     * The provider of the flight (e.g., airline, travel agency).
     */
    @Column(name = "provider")
    private String provider;

    /**
     * The discount percentage for the flight.
     */
    @Column(name = "discount", nullable = false, columnDefinition = "int default 0")
    private int discount;

    /**
     * The scheduled flight associated with this price.
     */
    @ManyToOne
    @JoinColumn(name = "scheduled_flights_id", nullable = false)
    private ScheduledFlights scheduledFlight;

    /**
     * Indicates whether the price is hidden or not.
     * Default value is false.
     */
    @Column(name = "is_hidden", nullable = false, columnDefinition = "BOOLEAN DEFAULT FALSE")
    private boolean isHidden;

    public Price() {
    }

    /**
     * Constructs a Price with the specified parameters.
     *
     * @param flightClassId   The flight class associated with this price.
     * @param price           The price of the flight.
     * @param currencyCode    The currency code for the price.
     * @param provider        The provider of the flight.
     * @param discount        The discount percentage for the flight.
     * @param scheduledFlight The scheduled flight associated with this price.
     */
    public Price(FlightClasses flightClassId, int price, String currencyCode, String provider, int discount,
            ScheduledFlights scheduledFlight) {
        this.flightClassId = flightClassId;
        this.price = price;
        this.currencyCode = currencyCode;
        this.provider = provider;
        this.discount = discount;
        this.scheduledFlight = scheduledFlight;
        this.isHidden = isHidden;
    }

    /**
     * Returns the unique identifier of the price.
     *
     * @return the ID of the price
     */
    public int getId() {
        return id;
    }

    /**
     * Sets the unique identifier of the price.
     *
     * @param id the ID to set
     */
    public void setId(int id) {
        this.id = id;
    }

    /**
     * Returns the flight class associated with this price.
     *
     * @return the flight class
     */
    public FlightClasses getFlightClassId() {
        return flightClassId;
    }

    /**
     * Sets the flight class associated with this price.
     *
     * @param flightClassId the flight class to set
     */
    public void setFlightClassId(FlightClasses flightClassId) {
        this.flightClassId = flightClassId;
    }

    /**
     * Returns the price of the flight.
     *
     * @return the price
     */
    public int getPrice() {
        return price;
    }

    /**
     * Sets the price of the flight.
     *
     * @param price the price to set
     */
    public void setPrice(int price) {
        this.price = price;
    }

    /**
     * Returns the currency code for the price.
     *
     * @return the currency code
     */
    public String getCurrencyCode() {
        return currencyCode;
    }

    /**
     * Sets the currency code for the price.
     *
     * @param currencyCode the currency code to set
     */
    public void setCurrencyCode(String currencyCode) {
        this.currencyCode = currencyCode;
    }

    /**
     * Returns the provider of the flight.
     *
     * @return the provider
     */
    public String getProvider() {
        return provider;
    }

    /**
     * Sets the provider of the flight.
     *
     * @param provider the provider to set
     */
    public void setProvider(String provider) {
        this.provider = provider;
    }

    /**
     * Returns the discount percentage for the flight.
     *
     * @return the discount percentage
     */
    public int getDiscount() {
        return discount;
    }

    /**
     * Sets the discount percentage for the flight.
     *
     * @param discount the discount percentage to set
     */
    public void setDiscount(int discount) {
        this.discount = discount;
    }

    /**
     * Returns the scheduled flight associated with this price.
     *
     * @return the scheduled flight
     */
    public ScheduledFlights getScheduledFlight() {
        return scheduledFlight;
    }

    /**
     * Sets the scheduled flight associated with this price.
     *
     * @param scheduledFlight the scheduled flight to set
     */
    public void setScheduledFlight(ScheduledFlights scheduledFlight) {
        this.scheduledFlight = scheduledFlight;
    }

    /**
     * Returns whether the price is hidden or not.
     *
     * @return true if the price is hidden, false otherwise
     */
    public boolean getIsHidden() {
        return isHidden;
    }

    /**
     * Sets whether the price is hidden or not.
     *
     * @param isHidden true to hide the price, false to show it
     */
    public void setIsHidden(boolean isHidden) {
        this.isHidden = isHidden;
    }
}
