package ntnu.no.stud.entities;

import jakarta.persistence.Entity;
import jakarta.persistence.Table;
import jakarta.persistence.Id;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Column;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.JoinColumn;
import java.time.LocalDate;

/**
 * Represents a scheduled flight entity, which is a many-to-many relationship
 * between flights and routes. Each scheduled flight has a unique identifier,
 * a specific flight, a specific route, and a date.
 */
@Entity
@Table(name = "scheduled_flights")
public class ScheduledFlights {

    /**
     * Unique identifier for the scheduled flight. Auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int id;

    /**
     * The flight associated with this scheduled flight.
     */
    @ManyToOne
    @JoinColumn(name = "flight_id", nullable = false)
    private Flight flight;

    /**
     * The route associated with this scheduled flight.
     */
    @ManyToOne
    @JoinColumn(name = "route_id", nullable = false)
    private Route route;

    /**
     * The date of the scheduled flight.
     */
    @Column(name = "date", nullable = false)
    private LocalDate date;

    public ScheduledFlights() {
    }

    /**
     * Constructs a ScheduledFlights with the specified flight, route, and date.
     *
     * @param flight The flight associated with this scheduled flight.
     * @param route  The route associated with this scheduled flight.
     * @param date   The date of the scheduled flight.
     */
    public ScheduledFlights(Flight flight, Route route, LocalDate date) {
        this.flight = flight;
        this.route = route;
        this.date = date;
    }

    /**
     * Returns the unique identifier of the scheduled flight.
     *
     * @return the ID of the scheduled flight
     */
    public int getId() {
        return id;
    }

    /**
     * Sets the unique identifier of the scheduled flight.
     *
     * @param id the ID to set
     */
    public void setId(int id) {
        this.id = id;
    }

    /**
     * Returns the flight associated with this scheduled flight.
     *
     * @return the flight associated with this scheduled flight
     */
    public Flight getFlight() {
        return flight;
    }

    /**
     * Sets the flight associated with this scheduled flight.
     *
     * @param flight the flight to set
     */
    public void setFlight(Flight flight) {
        this.flight = flight;
    }

    /**
     * Returns the route associated with this scheduled flight.
     *
     * @return the route associated with this scheduled flight
     */
    public Route getRoute() {
        return route;
    }

    /**
     * Sets the route associated with this scheduled flight.
     *
     * @param route the route to set
     */
    public void setRoute(Route route) {
        this.route = route;
    }

    /**
     * Returns the date of the scheduled flight.
     *
     * @return the date of the scheduled flight
     */
    public LocalDate getDate() {
        return date;
    }

    /**
     * Sets the date of the scheduled flight.
     *
     * @param date the date to set
     */
    public void setDate(LocalDate date) {
        this.date = date;
    }
}
