package ntnu.no.stud.entities;

import jakarta.persistence.CascadeType;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import java.util.HashSet;
import java.util.Iterator;
import java.util.Set;

import com.fasterxml.jackson.annotation.JsonManagedReference;

/**
 * Represents an application user.
 * Each user has a unique ID, username, password, email, and associated roles.
 */
@Entity
@Table(name = "user")
public class User {

    /**
     * Unique identifier for the user.
     * Automatically generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", nullable = false)
    private int id;

    /**
     * The username of the user. Must be unique and not null.
     */
    @Column(name = "username", nullable = false, unique = true)
    private String username;

    /**
     * The password of the user. Must not be null.
     */
    @Column(name = "password", nullable = false)
    private String password;

    /**
     * The email address of the user. Must be unique and not null.
     */
    @Column(name = "email", nullable = false, unique = true)
    private String email;

    /**
     * The roles assigned to the user.
     * Each role is a {@link UserRole} entity linked by a one-to-many relationship.
     */
    @OneToMany(mappedBy = "user", cascade = CascadeType.ALL, fetch = FetchType.EAGER, orphanRemoval = true)
    @JsonManagedReference
    private Set<UserRole> roles = new HashSet<>();

    private boolean active = true;

    /**
     * Default constructor required by JPA.
     */
    public User() {
    }

    /**
     * Constructs a new User with the given username, password, and email.
     *
     * @param username the user's username
     * @param password the user's password
     * @param email the user's email
     */
    public User(String username, String password, String email) {
        this.username = username;
        this.password = password;
        this.email = email;
    }

    // Getters and Setters
    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public Set<UserRole> getRoles() {
        return roles;
    }

    public void setRoles(Set<UserRole> roles) {
        this.roles = roles;
    }

    /**
     * Adds a role to the user and sets the back-reference.
     *
     * @param role the {@link UserRole} to add
     */
    public void addRole(UserRole role) {
        this.roles.add(role);
        role.setUser(this); // Set the user in the UserRole object
    }

    /**
     * Removes a role from the user and clears the back-reference.
     *
     * @param role the {@link UserRole} to remove
     */
    public void removeRole(UserRole role) {
        this.roles.remove(role);
        role.setUser(null); // Remove the user from the UserRole object
    }

    public boolean isActive() {
        return active;
    }

    public void setActive(boolean active) {
        this.active = active;
    }

    /**
     * Check if this user is an admin.
     *
     * @return True if the user has admin role, false otherwise
     */
    public boolean isAdmin() {
        return this.hasRole("ADMIN");
    }

    /**
     * Check if the user has a specified role.
     *
     * @param roleName Name of the role
     * @return True if hte user has the role, false otherwise.
     */
    public boolean hasRole(String roleName) {
        boolean found = false;
        Iterator<UserRole> it = roles.iterator();
        while (!found && it.hasNext()) {
            UserRole role = it.next();
            if (role.getRole().equalsIgnoreCase(roleName)) {
                found = true;
            }
        }
        return found;
    }
}
